import { describe, it, expect } from "vitest";
import { generateBusinessHTML, generateBusinessCSV, generateBusinessReport } from "./export";
import type { businesses, brandingResults, websiteResults, pricingResults, leadResults } from "../drizzle/schema";

describe("Export Functions", () => {
  const mockBusiness: typeof businesses.$inferSelect = {
    id: 1,
    userId: 1,
    name: "Crystal Clean Pressure Washing",
    serviceType: "Pressure Washing",
    targetMarket: "Residential homeowners",
    location: "Las Vegas, NV",
    businessGoals: "Build recurring revenue",
    status: "active",
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockBranding: typeof brandingResults.$inferSelect = {
    id: 1,
    businessId: 1,
    businessName: "Crystal Clean",
    tagline: "Sparkling Clean Guaranteed",
    brandVoice: "Professional and friendly",
    logoDescription: "Modern water droplet with shine effect",
    colorPalette: {
      primary: "#3b82f6",
      secondary: "#06b6d4",
      accent: "#10b981",
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockWebsite: typeof websiteResults.$inferSelect = {
    id: 1,
    businessId: 1,
    heroTitle: "Professional Pressure Washing",
    heroSubtitle: "Make Your Property Shine",
    heroDescription: "Expert pressure washing services for residential and commercial properties",
    featuresSectionCopy: "Fast, reliable, and affordable cleaning solutions",
    ctaText: "Get a Free Quote Today",
    seoTitle: "Professional Pressure Washing Services",
    seoDescription: "Expert pressure washing in Las Vegas",
    seoKeywords: "pressure washing, cleaning services",
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockPricing: typeof pricingResults.$inferSelect = {
    id: 1,
    businessId: 1,
    pricingStrategy: "Competitive hourly rates",
    recommendedTiers: [
      { name: "Basic", price: 150, description: "Small residential" },
      { name: "Standard", price: 300, description: "Large residential" },
      { name: "Premium", price: 500, description: "Commercial" },
    ],
    marketBenchmark: {
      "Small Residential": 150,
      "Large Residential": 300,
      Commercial: 500,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  const mockLeads: typeof leadResults.$inferSelect = {
    id: 1,
    businessId: 1,
    facebookAdCopy: "Get your property sparkling clean today!",
    googleAdCopy: "Professional pressure washing services",
    linkedinAdCopy: "Commercial cleaning solutions",
    emailSequence: "Email 1: Introduction\nEmail 2: Benefits\nEmail 3: CTA",
    smsScript: "Hi! Get 20% off your first cleaning. Book now!",
    leadMagnetIdeas: "Free cleaning estimate guide",
    createdAt: new Date(),
    updatedAt: new Date(),
  };

  it("should generate valid HTML", () => {
    const pkg = {
      business: mockBusiness,
      branding: mockBranding,
      website: mockWebsite,
      pricing: mockPricing,
      leads: mockLeads,
    };

    const html = generateBusinessHTML(pkg);

    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("Crystal Clean");
    expect(html).toContain("Sparkling Clean Guaranteed");
    expect(html).toContain("Professional Pressure Washing");
    expect(html).toContain("$150");
    expect(html).toContain("Get your property sparkling clean today!");
    expect(html).toContain("</html>");
  });

  it("should generate valid CSV", () => {
    const pkg = {
      business: mockBusiness,
      branding: mockBranding,
      website: mockWebsite,
      pricing: mockPricing,
      leads: mockLeads,
    };

    const csv = generateBusinessCSV(pkg);

    expect(csv).toContain("Business Information");
    expect(csv).toContain("Crystal Clean Pressure Washing");
    expect(csv).toContain("Pressure Washing");
    expect(csv).toContain("Las Vegas, NV");
    expect(csv).toContain("Pricing Strategy");
    expect(csv).toContain("Basic");
    expect(csv).toContain("$150");
    expect(csv).toContain("Lead Generation Templates");
  });

  it("should generate valid text report", () => {
    const pkg = {
      business: mockBusiness,
      branding: mockBranding,
      website: mockWebsite,
      pricing: mockPricing,
      leads: mockLeads,
    };

    const report = generateBusinessReport(pkg);

    expect(report).toContain("BUSINESS PACKAGE");
    expect(report).toContain("Crystal Clean");
    expect(report).toContain("BUSINESS OVERVIEW");
    expect(report).toContain("BRAND IDENTITY");
    expect(report).toContain("WEBSITE CONTENT");
    expect(report).toContain("PRICING STRATEGY");
    expect(report).toContain("LEAD GENERATION TEMPLATES");
    expect(report).toContain("Generated by BizBuildIt");
  });

  it("should handle missing data gracefully", () => {
    const pkg = {
      business: mockBusiness,
      branding: null,
      website: null,
      pricing: null,
      leads: null,
    };

    const html = generateBusinessHTML(pkg);
    const csv = generateBusinessCSV(pkg);
    const report = generateBusinessReport(pkg);

    expect(html).toContain("Crystal Clean Pressure Washing");
    expect(csv).toContain("Business Information");
    expect(report).toContain("BUSINESS OVERVIEW");
  });

  it("should escape special characters in CSV", () => {
    const pkg = {
      business: mockBusiness,
      branding: mockBranding,
      website: mockWebsite,
      pricing: mockPricing,
      leads: {
        ...mockLeads,
        facebookAdCopy: 'Quote "test" with special chars',
      },
    };

    const csv = generateBusinessCSV(pkg);

    expect(csv).toContain('Quote ""test"" with special chars');
  });
});
